sudo: required

language: java
jdk: oraclejdk8

services:
  - docker

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
    - SONAR_TOKEN=f5d62ebd1e835bac90caa240699795d0fcc29e70
    - DOCKER_USER=shboland
    - DOCKER_PASS=.widb-7e3Ndockerhub

addons:
  sonarcloud:
    organization: 
    token:
      secure: $SONAR_TOKEN

install:
  - mvn clean install

script:
  - sonar-scanner

after_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push shboland/api:1.0.0
