sudo: required

language: java
jdk: oraclejdk8

services:
  - docker

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
    - SONAR_TOKEN=eb21f40ecb59f211d58e51d1fea3f4516f73bfbc
    - DOCKER_USER=shboland
    - DOCKER_PASS=.widb-7e3Ndockerhub

addons:
  sonarcloud:
    organization: sybrenapitest-org
    token:
      secure: $SONAR_TOKEN

install:
  - mvn clean install

script:
  - sonar-scanner

after_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push shboland/api:1.0.0
